# Generated by Django 4.2.1 on 2023-05-20 23:58

from decimal import Decimal

from django.db import migrations

import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_price_alter_carmodel_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0')), djmoney.models.validators.MaxMoneyValidator(Decimal('999.990000000000009094947017729282379150390625'))]),
        ),
    ]
