# Generated by Django 4.2.1 on 2023-05-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='seller',
            new_name='user',
        ),
    ]
