# Generated by Django 4.2.1 on 2023-05-20 23:55

from django.db import migrations

import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('UAH', 'Hryvnia'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
