# Generated by Django 4.2.1 on 2023-05-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_seller_carmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='car_photo'),
        ),
    ]
