# Generated by Django 4.2.1 on 2023-05-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
