# Generated by Django 4.2.1 on 2023-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_carmodel_photo_carphotomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
