# Generated by Django 4.2.1 on 2023-05-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_options_carmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=20),
        ),
    ]
