# Generated by Django 4.2.1 on 2023-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carmodel_is_active_carmodel_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
